#!/usr/bin/env python3
"""End-to-end smoke test for the public Chatterbox-S3G decode API.

Calls codec_decode through the standard codec-cli (or, simpler, a small driver)
to confirm the public API path: tokens → mel → wav. Compares to a reference
generated by running the chatterbox PyTorch flow + HiFT and reports basic
audio-domain metrics."""

from __future__ import annotations

import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[2]
CONVERT = REPO_ROOT / "scripts" / "convert-to-gguf.py"
CODEC_CLI = REPO_ROOT / "build" / "codec-cli"
CHATTERBOX_DIR = REPO_ROOT / "models" / "chatterbox"


def run(cmd: list[str]) -> bytes:
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stderr.decode(errors='replace')[:4096]}")
    return proc.stdout


def read_wav(path: Path) -> tuple[np.ndarray, int]:
    with open(path, "rb") as f:
        data = f.read()
    sr = None
    pcm = None
    bits = None
    pos = 12
    while pos < len(data):
        cid = data[pos:pos + 4]
        size = struct.unpack_from("<I", data, pos + 4)[0]
        body = data[pos + 8: pos + 8 + size]
        if cid == b"fmt ":
            sr = struct.unpack_from("<I", body, 4)[0]
            bits = struct.unpack_from("<H", body, 14)[0]
        elif cid == b"data":
            pcm = body
        pos += 8 + size
        if size % 2:
            pos += 1
    assert pcm is not None and bits == 16
    return np.frombuffer(pcm, dtype=np.int16).astype(np.float32) / 32768.0, sr


def main() -> int:
    if not CODEC_CLI.is_file():
        print(f"SKIP: {CODEC_CLI} not built")
        return 0
    if not (CHATTERBOX_DIR / "s3gen.safetensors").is_file() or not (CHATTERBOX_DIR / "conds.pt").is_file():
        print(f"SKIP: {CHATTERBOX_DIR} not present")
        return 0

    with tempfile.TemporaryDirectory(prefix="codec-s3g-decode-") as td:
        td = Path(td)
        gguf = td / "s3g.gguf"
        run([sys.executable, str(CONVERT), "--checkpoint-path", str(CHATTERBOX_DIR), "--model-type", "chatterbox_s3g", "--output", str(gguf)])

        # codec-cli decode takes tokens as an .npy file [n_q, n_frames] int32.
        toks = np.array([[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000,
                          1100, 1200, 1300, 1400, 1500, 1600]], dtype=np.int32)
        npy_path = td / "tokens.npy"
        np.save(npy_path, toks)

        out_wav = td / "out.wav"
        run([str(CODEC_CLI), "decode", "--model", str(gguf), "--codes", str(npy_path), "--out", str(out_wav)])

        wav, sr = read_wav(out_wav)

    print(f"  decoded {wav.shape[0]} samples at {sr} Hz; rms={float(np.sqrt(np.mean(wav**2))):.4f}, peak={float(np.max(np.abs(wav))):.4f}")
    if not np.all(np.isfinite(wav)):
        print("FAIL: non-finite samples")
        return 1
    if np.max(np.abs(wav)) > 1.0:
        print("FAIL: clip exceeded ±1.0")
        return 1
    if np.sqrt(np.mean(wav**2)) < 1e-4:
        print("FAIL: silent output")
        return 1
    print("chatterbox S3G decode end-to-end smoke test passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
